language: rust
dist: trusty
addons:
  apt:
    packages:
      - libssl-dev

cache: cargo
rust:
  - nightly
  - beta
  - stable


script:
  - cargo clean
  - cargo build
  - cargo test

after_success: |
  if [[ "${TRAVIS_RUST_VERSION}" == stable ]]; then
    cargo install cargo-tarpaulin
    cargo tarpaulin --ciserver travis-ci --coveralls "${TRAVIS_JOB_ID}"
  fi
